# Generated by Django 3.2.7 on 2021-09-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanningService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SName', models.CharField(max_length=150)),
                ('SDesc', models.TextField(max_length=350)),
                ('SPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SIcon', models.CharField(blank=True, max_length=50)),
                ('SImage', models.ImageField(blank=True, upload_to='serviceimage')),
            ],
        ),
    ]
