# Generated by Django 3.2.7 on 2021-09-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleaningService', '0002_cleaningplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningplan',
            name='CPActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cleaningplan',
            name='CPStatus',
            field=models.CharField(choices=[('BC', 'BASIC CLEANING'), ('PC', 'PREMIUM CLEANING'), ('COMPLEX CLEANING', 'COMPLEX CLEANING')], default=(('BC', 'BASIC CLEANING'), ('PC', 'PREMIUM CLEANING'), ('COMPLEX CLEANING', 'COMPLEX CLEANING')), max_length=60),
        ),
    ]
