# Generated by Django 3.2.7 on 2021-09-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleaningService', '0003_auto_20210927_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningplan',
            name='CPActive',
            field=models.BooleanField(default=False),
        ),
    ]
