# Generated by Django 3.2.7 on 2021-09-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleaningService', '0004_alter_cleaningplan_cpactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningplan',
            name='CPActive',
        ),
        migrations.AddField(
            model_name='cleaningplan',
            name='CPFeatured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
    ]
