# Generated by Django 3.2.7 on 2021-09-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleaningService', '0006_servicepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepoint',
            name='SPAddress',
            field=models.CharField(max_length=200, verbose_name='Shop Address'),
        ),
        migrations.AlterField(
            model_name='servicepoint',
            name='SPPhone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Phone Number'),
        ),
    ]
