# Generated by Django 3.2.7 on 2021-09-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleaningService', '0007_auto_20210927_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EName', models.CharField(max_length=50, verbose_name='Employee Name')),
                ('Position', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=16)),
                ('ProfilePic', models.ImageField(upload_to='EProfilePic')),
                ('Twitter', models.URLField(verbose_name='Twitter Profile URL')),
                ('Facebook', models.URLField(verbose_name='Facebook Profile URL')),
                ('Linkedin', models.URLField(verbose_name='Linkedin Profile URL')),
                ('Instagram', models.URLField(verbose_name='Instagram Profile URL')),
            ],
        ),
    ]
