# Generated by Django 3.2.7 on 2021-10-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleaningService', '0008_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=40, verbose_name='Client Name')),
                ('CProfession', models.CharField(blank=True, max_length=70, verbose_name='Client Profession')),
                ('CComment', models.TextField(max_length=300, verbose_name='Client Comment')),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
