# Generated by Django 3.2.7 on 2021-10-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleaningService', '0009_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='CImage',
            field=models.ImageField(default='profile.png', upload_to='ClientImage'),
        ),
    ]
