# Generated by Django 3.2.7 on 2021-10-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleaningService', '0010_testimonial_cimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catitle', models.CharField(max_length=100, verbose_name='Title')),
                ('CaSubTitle', models.CharField(max_length=150, verbose_name='Subtitle')),
                ('CaDesc', models.TextField(max_length=300, verbose_name='Description')),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='cleaningplan',
            name='CPItems',
            field=models.ManyToManyField(to='CleaningService.CleanningService', verbose_name='Cleaning Items'),
        ),
        migrations.AlterField(
            model_name='cleaningplan',
            name='CPName',
            field=models.CharField(max_length=100, verbose_name='Cleaning Plan Name'),
        ),
        migrations.AlterField(
            model_name='cleaningplan',
            name='CPPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='cleaningplan',
            name='CPStatus',
            field=models.CharField(choices=[('BC', 'BASIC CLEANING'), ('PC', 'PREMIUM CLEANING'), ('COMPLEX CLEANING', 'COMPLEX CLEANING')], default=(('BC', 'BASIC CLEANING'), ('PC', 'PREMIUM CLEANING'), ('COMPLEX CLEANING', 'COMPLEX CLEANING')), max_length=60, verbose_name='Plan Status'),
        ),
        migrations.AlterField(
            model_name='cleanningservice',
            name='SDesc',
            field=models.TextField(max_length=350, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cleanningservice',
            name='SIcon',
            field=models.CharField(blank=True, default='flaticon-car-wash', max_length=50, verbose_name='Icon Class Name'),
        ),
        migrations.AlterField(
            model_name='cleanningservice',
            name='SImage',
            field=models.ImageField(blank=True, upload_to='serviceimage', verbose_name='Service Image'),
        ),
        migrations.AlterField(
            model_name='cleanningservice',
            name='SName',
            field=models.CharField(max_length=150, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='cleanningservice',
            name='SPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Service Price'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='CImage',
            field=models.ImageField(default='profile.png', upload_to='ClientImage', verbose_name='Client Image'),
        ),
    ]
