# Generated by Django 3.2.7 on 2021-10-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleaningService', '0011_auto_20211001_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='CaImage',
            field=models.ImageField(default='carousel.jpg', upload_to='carousel', verbose_name='Image'),
        ),
    ]
