# Generated by Django 3.2.7 on 2021-10-01 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CleaningService', '0012_carousel_caimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Atitle', models.CharField(max_length=100, verbose_name='Title')),
                ('AImage', models.ImageField(default='carousel.jpg', upload_to='carousel', verbose_name='Image(H:650px,W:600px)')),
                ('ADesc', models.TextField(max_length=300, verbose_name='Description')),
                ('Status', models.BooleanField(default=False)),
                ('Auser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('SItem', models.ManyToManyField(to='CleaningService.CleanningService', verbose_name='Service Items')),
            ],
        ),
    ]
