# Generated by Django 3.2.7 on 2021-10-01 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CleaningService', '0013_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_time', models.CharField(max_length=100, verbose_name='Office Day and Time')),
                ('Number', models.CharField(blank=True, max_length=15, verbose_name='Quick Contact Number')),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='Auser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
