# Generated by Django 3.2.7 on 2021-10-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleaningService', '0015_auto_20211002_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
