# Generated by Django 3.2.7 on 2021-10-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleaningService', '0016_office_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='Office_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Office Name'),
        ),
    ]
