# Generated by Django 3.2.7 on 2021-10-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleaningService', '0017_office_office_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='Office_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Office Location'),
        ),
    ]
